//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO20K.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ci()
        {
            this.ci_family_application = new HashSet<ci_family_application>();
            this.ci_family_employee = new HashSet<ci_family_employee>();
            this.ci_family_hardware = new HashSet<ci_family_hardware>();
            this.ci_family_service = new HashSet<ci_family_service>();
            this.ci_family_system = new HashSet<ci_family_system>();
            this.ci_log = new HashSet<ci_log>();
        }
    
        public int ci_id { get; set; }
        public string name { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int family_id { get; set; }
        public int severity_id { get; set; }
        public int org_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public string description { get; set; }
    
        public virtual ci_family ci_family { get; set; }
        public virtual ci_severity ci_severity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ci_family_application> ci_family_application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ci_family_employee> ci_family_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ci_family_hardware> ci_family_hardware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ci_family_service> ci_family_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ci_family_system> ci_family_system { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ci_log> ci_log { get; set; }
    }
}
