//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO20K.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ci_family_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ci_family_employee()
        {
            this.ci_log = new HashSet<ci_log>();
            this.@operator = new HashSet<@operator>();
        }
    
        public int employee_id { get; set; }
        public string name { get; set; }
        public int ci_id { get; set; }
        public string mobile_number { get; set; }
        public string email { get; set; }
    
        public virtual ci ci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ci_log> ci_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@operator> @operator { get; set; }
    }
}
