//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO20K.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISO20_DBEntities : DbContext
    {
        public ISO20_DBEntities()
            : base("name=ISO20_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ci> ci { get; set; }
        public virtual DbSet<ci_family> ci_family { get; set; }
        public virtual DbSet<ci_family_application> ci_family_application { get; set; }
        public virtual DbSet<ci_family_employee> ci_family_employee { get; set; }
        public virtual DbSet<ci_family_hardware> ci_family_hardware { get; set; }
        public virtual DbSet<ci_family_service> ci_family_service { get; set; }
        public virtual DbSet<ci_family_system> ci_family_system { get; set; }
        public virtual DbSet<ci_log> ci_log { get; set; }
        public virtual DbSet<ci_opcode> ci_opcode { get; set; }
        public virtual DbSet<ci_severity> ci_severity { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<@operator> @operator { get; set; }
        public virtual DbSet<operation_privilege> operation_privilege { get; set; }
    }
}
